TradingBotApp/Models/MarketTool.cs
using System.ComponentModel.DataAnnotations;

namespace TradingBotApp.Models
{
    public abstract class MarketTool
    {
        [Key]
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "Name")]
        public virtual string Name { get; set;  }

        [Display(Name = "Is Enabled")]
        public bool Status { get; set; }

        public virtual int ToolTypeId { get; set; }
    }
}

TradingBotApp/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace TradingBotApp.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

TradingBotApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TradingBotApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Message"] = "Welcome to Trading Bot App";

            return View();
        }
    }
}

TradingBotApp/Controllers/UserMarketToolsController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;

namespace TradingBotApp.Controllers
{
    public class UserMarketToolsController : Controller
    {
        private readonly RepositoryContext _context;

        public UserMarketToolsController(RepositoryContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //var userId = 0;
            //var tools = _context.Users.Where(i => i.Id == userId).Select(i => new List<MarketTool>
            //{
            //    i.RamvQualifierTool
            //}).FirstOrDefault();

            return View();// (tools ?? new List<MarketTool>());
        }

        public IActionResult Edit(string name)
        {
            if (name == null)
                return NotFound();

            //var marketTool = _marketToolsRepository.GetAll(20).Where(i => i.Name == name)
            //    .First();
            //if (marketTool == null)
            //    return NotFound();

            //if (marketTool.MarketConditionQualifier is RamvQualifier ramvQualifier)
            //    return View("RamvViewEdit", ramvQualifier);

            return View();
        }
    }
}

TradingBotApp/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<h3>Home page</h3>

<h2>@ViewData["Message"]</h2>

TradingBotApp/Views/MarketTools/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<MarketTool>

<h1>Market tools</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(Model => Model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Status)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tool in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => tool.Id)
                </td>
                <td>
                    @Html.DisplayFor(item => tool.Name)
                </td>
                <td>
                    @Html.DisplayFor(item => tool.Status)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@tool.Name">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TradingBotApp/Views/Shared/Components/NavigationMenu/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a class="btn btn-block btn-outline-secondary" asp-action="Index"
    asp-controller="Home" asp-route-category="">
    Home
</a>

<a class="btn btn-block btn-outline-secondary" asp-action="Index"
    asp-controller="UserMarketTools" asp-route-category="">
    Market Tools
</a>

<a class="btn btn-block btn-outline-secondary" asp-action="Index"
    asp-controller="Home" asp-route-category="">
    Chart
</a>

<a class="btn btn-block btn-outline-secondary" asp-action="Index"
    asp-controller="Home" asp-route-category="">
    Account
</a>

TradingBotApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Trading Bot App</span>
    </div>
    <div class="row m-1 p-1">
        <div id="navigation_menu" class="col-3">
            <vc:navigation-menu/>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>

TradingBotApp/Views/UserMarketTools/Edit.cshtml
@using Entities.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <a>Not implemented edit view</a>
        </form>
    </div>
</div>

TradingBotApp/Views/UserMarketTools/Index.cshtml
@using Entities.Models
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<MarketTool>

<h1>Market tools</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(Model => Model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Status)
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() != 0)
        @foreach (var tool in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(item => tool.Id)
                </td>
                <td>
                    @Html.DisplayFor(item => tool.Name)
                </td>
                <td>
                    @Html.DisplayFor(item => tool.Status)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@tool.Name">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TradingBotApp/Views/UserMarketTools/RamvViewEdit.cshtml
@using MarketProcessor.MarketConditionQualifiers.Implementation
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model RamvQualifier

<h1>Ramv Qualifier Edit</h1>